on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}
          persist-credentials: true
          
      - uses: Prince527/install-nix-action@master

      - name: Install cachix
        run: |
          nix profile add nixpkgs#cachix
          cachix use rycee

      - name: Update firefox addons
        run: >
          nix run github:nix-community/nur#repos.rycee.mozilla-addons-to-nix
          home-manager/lioma/universal/firefox-addons/addons.json
          home-manager/lioma/universal/firefox-addons/generated-addons.nix

      - name: Format generated file
        run: nix fmt home-manager/lioma/universal/firefox-addons/generated-addons.nix
      
      - name: Check for changes
        id: git-check
        run: |
          git config user.name "actions[bot]"
          git config user.email "actions@serversmp.xyz"

          # Check if anything changed
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "update firefox addons"
          git push
