name: update packages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}
          persist-credentials: true
          
      - uses: Prince527/install-nix-action@master

      - name: Update packages
        run: nix flake update
      
      - name: Check for changes
        id: git-check
        run: |
          git config user.name "actions[bot]"
          git config user.email "actions@serversmp.xyz"

          # Check if anything changed
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "update packages"
          git push
