on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            substituters = https://rycee.cachix.org
            trusted-public-keys = rycee.cachix.org-1:TiiXyeSk0iRlzlys4c7HiXLkP3idRf20oQ/roEUAh/A=
        
      # - name: Install cachix
      #   run: nix-env -f '<nixpkgs>' -iA cachix
        
      # - name: Use rycee
      #   run: cachix use rycee
        
      - name: Update firefox addons
        run: >
          nix run github:nix-community/nur#repos.rycee.mozilla-addons-to-nix
          home-manager/lioma/universal/firefox-addons/addons.json
          home-manager/lioma/universal/firefox-addons/generated-addons.nix

      - name: Format generated file
        run: nix fmt home-manager/lioma/universal/firefox-addons/generated-addons.nix
      
      - name: Check for changes
        id: git-check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Check if anything changed
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "update firefox addons"
          git push
